AooniJinrou:
  Setting:
    Job:
      aooni: 3
      hunter: 1
      mika: 1
      takeshi: 1
      takurou: 1
    Game:
      Time: 1200
      World: "world"
  Location:
    world:
      Start:
        [50,64,50]
      Gate:
        UnderFloor:
          [50,60,60]
        TopFloor:
          [30,80,10]
      Chest:
        Floor-1:
          - [100, 64, -200]
          - [50, 64, -200]
        Floor1:
          - [ 10, 64, -200]
          - [ 120, 64, -200]
