AooniJinrou:
  Setting:
    Job:
      AOONI: 3
      HUNTER: 1
      MIKA: 1
      TAKESHI: 1
      TAKUROU: 1
    Game:
      Time: 1200
      World: world
  Location:
    world:
      Start:
        [50,64,50]
      Gate:
        UnderFloor:
          [280, 57, 89]
        TopFloor:
          [242,75,82]
      Plate:
        SilverKey:
          [284, 83, 130]
      Chest:
        Floor-1:
          - [100, 64, -200]
          - [50, 64, -200]
        Floor4:
          - [ 237, 76, 89]
          - [ 258, 78, 94]
